variables:
  PLUGIN: 'report_gwpayments'
  PATHNAME: 'report/gwpayments/coupon'
  REPOURL: 'https://github.com/sebsoftnl/moodle-report_gwpayments'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
